app/Http/routes.php
<?php
/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */


//$router->resource('services.followup', 'Services\ServiceFollowUpController');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


$router->get('/', function () {

    return redirect('/auth/login');
});

$router->get('/home', function () {
    return redirect()->route('cases.index');
});


$router->get('download/{filename}',function($filename){
    $filePath = public_path().'/uploads/temp/'.$filename;
    if (file_exists($filePath))
    {
        // Send Download
        return Response::download($filePath, $filename, [
            'Content-Length: '. filesize($filePath)
        ]);
    }
    else
    {
        // Error
        exit('Requested file does not exist on our server!');
    }
});
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);



$router->group(['middleware' => ['auth', 'acl']],
    function ($router) {

        $router->group(['namespace' => 'Users', 'permissions' => ['manage-all', 'manage-users']],
        function ($router) {
        $router->resource('users', 'UsersController');
    });

    $router->group(['namespace' => 'Users', 'permissions' => ['manage-all', 'manage-roles']],
        function ($router) {
        $router->resource('role', 'RoleController');
    });

    $router->group(['namespace' => 'Cases'],
        function ($router) {
        $router->get('cases/delete/{caseId}',
            [
            'as' => 'cases.delete',
            'uses' => 'CaseController@delete',
        ]);
        $router->resource('cases', 'CaseController');
    });

    $router->group(['namespace' => 'Services'],
        function ($router) {
        $router->get('/cases/{caseId}/service/{type}/create',
            [
            'as' => 'services.create',
            'uses' => 'ServiceController@create',
        ]);
        $router->get('/cases/{caseId}/service/{type}',
            [
            'as' => 'services.show',
            'uses' => 'ServiceController@show',
        ]);
        $router->get('/service/{serviceId}/edit',
            [
            'as' => 'services.edit',
            'uses' => 'ServiceController@edit',
        ]);
        $router->put('/service/{serviceId}',
            [
            'as' => 'services.update',
            'uses' => 'ServiceController@update',
        ]);
        $router->resource('cases.services', 'ServiceController');
         $router->resource('services.followup', 'ServiceFollowUpController');


            $router->get('service/{serviceId}/delete',
            [
            'as' => 'services.delete',
            'uses' => 'ServiceController@delete',
        ]);
    });
    $router->group(['namespace' => 'Log', 'permissions' => ['manage-all', 'manage-activity-log']],
        function($router) {
        $router->resource('log', 'ActivityLogController');
    });


    $router->post('file/uploads',
        [
        'as' => 'file.uploads',
        'uses' => 'FileController@upload',
    ]);
    $router->post('file/remove',
        [
        'as' => 'file.remove',
        'uses' => 'FileController@remove',
    ]);

//    $router->get('download/{filename}',[
//        'uses' => 'FileController@downloadFile'
//    ]);

});

app/Models/Service/ServiceFile.php
<?php namespace App\Models\Service;

use Illuminate\Database\Eloquent\Model;

class ServiceFile extends Model {

	protected $table = "service_files";
	protected $fillable = ['service_id','file_name','file_path'];

	public function cases(){
		return $this->belongsTo('App\Models\Service\Service');
	}

}

app/Models/Service/ServiceFollowUp.php
<?php

namespace App\Models\Service;

use Illuminate\Database\Eloquent\Model;
use Regulus\ActivityLog\Models\Activity;

class ServiceFollowUp extends Model
{
    protected $fileable_key = "service_follow_up";
    protected $table        = "service_follow_up";
    protected $fillable     = ['user_id', 'case_id', 'description', 'date'];

    public function service()
    {
        return $this->belongsTo('\App\Models\Service\Service', 'service_id');
    }

    public function files()
    {
        return $this->morphMany('App\Models\File', 'fileable');
    }

    public function getFileKey()
    {
        return $this->fileable_key;
    }

    public function activityLogForCreate()
    {
        $userName = \Auth::user()->name;
        Activity::log([
            'contentId' => $this->id,
            'contentType' => $this->service->service,
            'action' => 'Store',
            'description' => "$userName added 'Follow up' for ".$this->service->title." of Case #".$this->service->cases->reg_no,
            'details' => "$userName added 'Follow up' for ".$this->service->title." of Case #".$this->service->cases->reg_no,
            'updated' => '',
        ]);
    }

    public function activityLogForUpdate()
    {
        $userName = \Auth::user()->name;
        Activity::log([
            'contentId' => $this->id,
            'contentType' => $this->service->service,
            'action' => 'Update',
            'description' => "$userName updated 'Follow up' for ".$this->service->title." of Case #".$this->service->cases->reg_no,
            'details' => "$userName updated 'Follow up' for ".$this->service->title." of Case #".$this->service->cases->reg_no,
            'updated' => '',
        ]);
    }
}

app/Http/Controllers/Services/ServiceController.php
<?php

namespace App\Http\Controllers\Services;

use App\Core\Organization\Organization;
use App;
use App\Helpers\JsonHelper;

use App\Http\Requests\Service\CreateServiceRequest;
use App\Models\Service\Service;
use Illuminate\Routing\Controller;
use App\Models\Cases\Cases;
use App\Helpers\FileHelper;
use App\Models\File as ServiceFile;
use Illuminate\Support\Facades\Response;

/**
 * Class ServiceController
 * @package App\Http\Controllers\Services
 */
class ServiceController extends Controller
{

    public function __construct(Organization $organization, Cases $case, Service $service)
    {
        $this->organization = $organization;
        $this->formBuilderObj = App::make('FormBuilder');
        $this->case = $case;
        $this->service = $service;
        $this->fileHelper = new FileHelper;
        $this->serviceFile = new ServiceFile();
    }

    public function create($caseId, $type)
    {
        $this->service->case_id = $caseId;
        $this->service->service = $type;
        $this->organization->setSection($type);
        $this->service->title   = $this->organization->getServiceTitle();
        $formPath               = $this->organization->getFormPath();
        $form                   = $this->formBuilderObj->create($formPath,
            [
            'method' => 'POST',
            'url' => route('cases.services.store', $caseId),
            'model' => $this->service,
            'data' => ['caseId' => $caseId, 'organizationObj' => $this->organization],
            'class' => 'form-class file-upload-form ajax-validate',
        ]);
        $form->add('service', 'hidden', ['default_value' => $this->service->service]);
        $service = $this->service;
        //dd($form);
        return view("services.create", compact('form', 'service'));
    }

    public function store(CreateServiceRequest $request, $caseId)
    {
        $service = $this->service;
        $service->case_id = $caseId;
        $service->user_id = \Auth::user()->id;
        $service->fill($request->only('service', 'date'));
        $service->details = JsonHelper::JsonEncode($request->get('details'));
        $service->save();
        $this->organization->setSection($service->service);
        $service->title = $this->organization->getServiceTitle();
        $service->activityLogForCreate();
        if ($request->get('files')) {
            $this->fileHelper->moveFiles($service, $request->get('files'));
        }
        if ($service->service == "FollowUp") {
            $flashMessage = "Follow up of Case #" . $service->cases->reg_no . " is added successfully";
        } else {
            $flashMessage = $service->title." is added successfully to Case #".$service->cases->reg_no;
        }
        \Flash::success($flashMessage);

        return Response::json([
                'url' => route('cases.show', $caseId),
        ]);
    }

    public function show($caseId, $type)
    {
        $service = $this->service->whereCaseId($caseId)->whereService($type)->firstOrFail();
        $service->details = JsonHelper::JsonDecode($service->details);
        return view("services." . $type . "_show", compact('service'));
    }

    public function edit($serviceId)
    {
        $service          = $this->service->findOrFail($serviceId);
        $service->details = JsonHelper::JsonDecode($service->details);
        $this->organization->setSection($service->service);
        $formPath         = $this->organization->getFormPath();
        $service->user_id = \Auth::user()->id;
        $this->organization->setSection($service->service);
        $service->title   = $this->organization->getServiceTitle();
        $form             = $this->formBuilderObj->create($formPath,
            [
            'method' => 'PUT',
            'url' => route('services.update', $serviceId),
            'model' => $service,
            'data' => ['caseId' => $service->case_id, 'organizationObj' => $this->organization],
            'class' => 'form-class file-upload-form ajax-validate',
        ]);
        $form->add('service', 'hidden', ['default_value' => $service->service]);

        return view("services.create", compact('form', 'service'));
    }

    public function update(CreateServiceRequest $request, $serviceId)
    {
        $service = $this->service->findOrFail($serviceId);
        $service->fill($request->only('service', 'date'));
        $service->details = JsonHelper::JsonEncode($request->get('details'));
        $this->updateFiles($request->get('uploaded_files'), $service); 
        if ($request->get('files')) {
            $this->fileHelper->moveFiles($service, $request->get('files'));
        }
        $service->save();
        $this->organization->setSection($service->service);
        $service->title = $this->organization->getServiceTitle();
        $service->activityLogForUpdate();
        if ($service->service == "FollowUp") {
            $flashMessage = "Follow up of Case #" . $service->cases->reg_no . " is edited successfully";
        } else {
            $flashMessage = $service->title . " is edited successfully of Case #".$service->cases->reg_no;
            \Flash::success($flashMessage);
        }

        return Response::json([
                'url' => route('cases.show', $service->case_id),
        ]);
    }

    public function delete($serviceId)
    {
        $service = $this->service;
        if (\Auth::user()->can(['delete-own-services'])) {
            $service = $service->where('user_id', '=', \Auth::user()->id);
        }
        $service = $service->findOrFail($serviceId);
        $service->deleteService();        
        $this->organization->setSection($service->service);
        $service->title = $this->organization->getServiceTitle();
        $service->activityLogForDelete();
        $flashMessage = "$service->title is deleted successfully of Case #".$service->cases->reg_no;
        \Flash::success($flashMessage);

        return redirect()->route('cases.show', $service->case_id);
    }

    private function updateFiles($uploadedFiles = [], $service)
    {
        $files = $service->files;
        if (empty($uploadedFiles)) {
            foreach ($files as $file) {
                $this->removeFiles($file);
            }

            return true;
        }
        foreach ($files as $file) {
            if (!in_array($file->file_name, $uploadedFiles)) {
                $this->removeFiles($file);
            }
        }
    }

    private function removeFiles($file)
    {
        \File::delete(public_path().$file->file_path);
        $this->serviceFile->find($file->id)->delete();
    }
}

app/Http/Controllers/Services/ServiceFollowUpController.php
<?php

namespace App\Http\Controllers\Services;

use App\Core\Organization\Organization;
use App\Http\Requests\Service\FollowUpRequest;
use App\Models\Service\Service;
use App\Models\Service\ServiceFollowUp;
use Illuminate\Routing\Controller;
use App\Helpers\FileHelper;
use App\Core\Form\FormBuilder;
use App;

class ServiceFollowUpController extends Controller
{

    public function __construct(Organization $organization, Service $service,
                                ServiceFollowUp $followUp)
    {
        $this->organization = $organization;
        $this->service      = $service;
        $this->followup     = $followUp;
        $this->fileHelper   = new FileHelper();
    }

    public function create($serviceId)
    {
        $this->followup->service_id     = $serviceId;
        $formBuilder                    = App::make('FormBuilder');
        $form                           = $formBuilder->create('App\Forms\Services\ServiceFollowUp',
            [
            'method' => 'POST',
            'url' => route('services.followup.store', $serviceId),
            'model' => $this->followup,
            'data' => ['organizationObj' => $this->organization],
            'class' => 'form-class',
        ]);
        $followup                       = $this->followup;
        $this->organization->setSection($this->followup->service->service);
        $this->followup->service->title = $this->organization->getServiceTitle();

        return view('services.follow_up_create', compact('form', 'followup'));
    }

    public function store(FollowUpRequest $request, $serviceId)
    {
        $followup             = $this->followup;
        $followup->fill($request->only('description', 'date'));
        $followup->service_id = $serviceId;
        $followup->user_id    = \Auth::user()->id;
        $followup->save();
        if ($request->file('files')) {
            $this->fileHelper->storeFiles($followup, $request->file('files'));
        }
        $this->saveToServices($followup);
        $this->organization->setSection($this->followup->service->service);
        $followup->service->title = $this->organization->getServiceTitle();
        $followup->activityLogForCreate();
        \Flash::success("Follow up for ".$followup->service->title." of Case #".$followup->service->cases->reg_no."  is added successfully.");

        return redirect()->route('cases.show', $followup->service->case_id);
    }

    public function edit($serviceId, $followupId)
    {
        $followup    = $this->followup->findOrFail($followupId);
        $formBuilder = new FormBuilder();
        $form        = $formBuilder->create('App\Forms\Services\ServiceFollowUp',
            [
            'method' => 'PUT',
            'url' => route('services.followup.update',
                [$serviceId, $followup->id]),
            'model' => $followup,
            'data' => ['organizationObj' => $this->organization],
            'class' => 'form-class',
        ]);

        return view('services.follow_up_create', compact('form', 'followup'));
    }

    public function update(FollowUpRequest $request, $serviceId, $followupId)
    {
        $followup = $this->followup->findOrFail($followupId);
        $followup->fill($request->only('description', 'date'));
        $followup->save();
        if ($request->file('files')) {
            $this->fileHelper->storeFiles($this->followup,
                $request->file('files'));
        }
        $this->updateToServices($followup);
        $this->organization->setSection($followup->service->service);
        $followup->service->title = $this->organization->getServiceTitle();
        $followup->activityLogForUpdate();
        \Flash::success("Follow up for " .$followup->service->title. " of Case #" . $followup->service->cases->reg_no . "  is edited successfully.");

        return redirect()->route('cases.show', $followup->service->case_id);
    }

    private function saveToServices($followup)
    {
        $this->service->follow_up_id = $followup->id;
        $this->service->date         = $followup->date;
        $this->service->case_id      = $followup->service->case_id;
        $this->service->user_id      = \Auth::user()->id;
        $this->service->service      = "service_followup";
        $this->service->save();

        return true;
    }

    private function updateToServices($followup)
    {
        $this->service       = $this->service->findOrFail($followup->service_id);
        $this->service->date = $followup->date;
        $this->service->save();

        return true;
    }

    public function delete($followUpId)
    {
        $service = $this->service->findOrFail($serviceId);
        foreach ($service->files as $servicefiles) {
            \File::delete($servicefiles->file_path);
        }
        foreach ($service->followups as $followup) {
            foreach ($followup->files as $followUpFiles) {
                \File::delete($followUpFiles->file_path);
            }
        }
        $service->files()->delete();
        $service->followups()->delete();
        $service->followup()->delete();
        $service->delete();
        \Flash::success("Service deleted successfully");

        return redirect()->route('cases.show', $service->case_id);
    }
}

resources/views/services/partials/_followUp.blade.php
<?php $details = JsonHelper::JsonDecode($service->details)?>
<p>{!!nl2br($details->description)!!}</p>

resources/views/services/partials/_serviceDetails.blade.php
<?php
echo nl2br($serviceGenerator->generate($service,$service->service));

?>

resources/views/services/partials/_service_followup.blade.php
@if($service->followup)

    <div class="followup-heading">
        <div class="title">
            Follow up <a
                    id="{{$service->followup->service->id}}link">( {{$services[$service->followup->service->service]['label']}}
                )</a>
        </div>
        <div class="button-block">
            @if( Entrust::can('manage-all') || Entrust::can('manage-all-services') || (Entrust::can('manage-own-services') && \Auth::user()->id == $service->followup->service->user_id ))
                {!! link_to_route('services.followup.edit',
                "Edit",[$service->followup->service->id,$service->followup->id],['class'=>'edit-btn']) !!}
                @if(\Auth::user()->can(['manage-all', 'delete-all-services']) || (\Auth::user()->can('delete-own-services') && \Auth::user()->id == $service->followup->service->user_id ))
                    {!! link_to_route('services.delete',
                    "Delete",$service->id,['class'=>'delete-btn','data-method'=>'delete']) !!}
                    @if(Entrust::can('delete-all-services') && Entrust::can('delete-own-services'))
                        {!! link_to_route('services.delete',
                        "Delete",$service->id,['class'=>'delete-btn','data-method'=>'delete']) !!}
                    @endif
                @endif
             @endif
        </div>
    </div>
    <p>{!!nl2br($service->followup->description)!!}</p>
    @if(count($service->followup->files))
        <ul class="follow-list">
            <li>
                <label for="">Files</label>
                @foreach($service->followup->files as $serviceFile)
                    <div class="followup-description">
                        <a href="{{asset($serviceFile->file_path)}}" target="_blank">{{$serviceFile->file_name}}</a>
                    </div>
                @endforeach
            </li>
        </ul>
    @endif
@endif

resources/views/services/partials/_services.blade.php
<div class="followup-heading">
    <div class="title" id="{{$service->id}}">{{$services[$service->service]['label']}}</div>
    <div class="button-block">
        @if($service->service != 'FollowUp' && !isset($services[$service->service]['followup']) && ! \Auth::user()->can('view-all-services'))
        {!! link_to_route('services.followup.create', "Follow up",$service->id,['class'=>'followup-btn']) !!}
        @endif

        @if(\Auth::user()->can('manage-all') || \Auth::user()->can('manage-all-services') || (\Auth::user()->can('manage-own-services') && \Auth::user()->id == $service->user_id ) )
            {!! link_to_route('services.edit', "Edit",$service->id,['class'=>'edit-btn']) !!}
        @if(\Auth::user()->can(['manage-all', 'delete-all-services']) || (\Auth::user()->can('delete-own-services') && \Auth::user()->id == $service->user_id ))
        {!! link_to_route('services.delete', "Delete",$service->id,['class'=>'delete-btn','data-method'=>'delete']) !!}
        @endif
        @endif
    </div>
</div>


@if(isset($services[$service->service]['followUpTemplate']) && !$services[$service->service]['followUpTemplate'])
<?php  $viewFileExist = View::exists("Fightvaw::Services.partials._".$service->service); ?>
@if($viewFileExist)
@include("Fightvaw::Services.partials._".$service->service)
@else
@include("services.partials._serviceDetails")
@endif
@else
@include("services.partials._followUp")
@endif

<!-- Service Followup -->
@if($service->service != 'FollowUp')
@include("services.partials.service_follow_up")
@endif

@if(count($service->files))
<!-- Service Files -->
<ul class="follow-list file-lists">
    <li>
        <label>Files</label>
        @foreach($service->files as $file)
        <div class="followup-description">
            <a href="{{ url('download',[md5($file->file_name)."_".$file->file_name])}}" target="_blank"> @if(strlen($file->file_name) >= 20) {{substr($file->file_name,0,20)."... ".substr($file->file_name,-5)}} @else {{ $file->file_name }} @endif</a>
        </div>
        @endforeach
    </li>
</ul>
@endif

resources/views/services/partials/service_follow_up.blade.php
@if(count($service->followups) > 0)
<ul class="follow-list">
    <li>
        <label for="">Follow up</label>
        @foreach($service->followups as $followup)
            <div class="followup-description">
                <div class="date">{{ViewHelper::formatDate($followup->date)}}</div>
                {!!nl2br($followup->description)!!}

                @if(count($followup->files))
                    <ul class="follow-list">
                        <li>
                            <label for="">Files</label>
                            @foreach($followup->files as $serviceFile)
                                <div class="followup-description followup-files">
                                    <a href="{{asset($serviceFile->file_path)}}" target="_blank">{{$serviceFile->file_name}}</a>
                                </div>
                            @endforeach
                        </li>
                    </ul>
                @endif
                
            </div>
        @endforeach
    </li>
</ul>
@endif